// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package os

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OSReaderClient is the client API for OSReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSReaderClient interface {
	GetOneByID(ctx context.Context, in *GetOneByIDRequest, opts ...grpc.CallOption) (*GetOneByIDResponse, error)
	GetManyByIDs(ctx context.Context, in *GetManyByIDsRequest, opts ...grpc.CallOption) (*GetManyByIDsResponse, error)
	ListByCursor(ctx context.Context, in *ListByCursorRequest, opts ...grpc.CallOption) (*ListByCursorResponse, error)
	ListByPage(ctx context.Context, in *ListByPageRequest, opts ...grpc.CallOption) (*ListByPageResponse, error)
}

type oSReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewOSReaderClient(cc grpc.ClientConnInterface) OSReaderClient {
	return &oSReaderClient{cc}
}

func (c *oSReaderClient) GetOneByID(ctx context.Context, in *GetOneByIDRequest, opts ...grpc.CallOption) (*GetOneByIDResponse, error) {
	out := new(GetOneByIDResponse)
	err := c.cc.Invoke(ctx, "/os.OSReader/GetOneByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSReaderClient) GetManyByIDs(ctx context.Context, in *GetManyByIDsRequest, opts ...grpc.CallOption) (*GetManyByIDsResponse, error) {
	out := new(GetManyByIDsResponse)
	err := c.cc.Invoke(ctx, "/os.OSReader/GetManyByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSReaderClient) ListByCursor(ctx context.Context, in *ListByCursorRequest, opts ...grpc.CallOption) (*ListByCursorResponse, error) {
	out := new(ListByCursorResponse)
	err := c.cc.Invoke(ctx, "/os.OSReader/ListByCursor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSReaderClient) ListByPage(ctx context.Context, in *ListByPageRequest, opts ...grpc.CallOption) (*ListByPageResponse, error) {
	out := new(ListByPageResponse)
	err := c.cc.Invoke(ctx, "/os.OSReader/ListByPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSReaderServer is the server API for OSReader service.
// All implementations must embed UnimplementedOSReaderServer
// for forward compatibility
type OSReaderServer interface {
	GetOneByID(context.Context, *GetOneByIDRequest) (*GetOneByIDResponse, error)
	GetManyByIDs(context.Context, *GetManyByIDsRequest) (*GetManyByIDsResponse, error)
	ListByCursor(context.Context, *ListByCursorRequest) (*ListByCursorResponse, error)
	ListByPage(context.Context, *ListByPageRequest) (*ListByPageResponse, error)
	mustEmbedUnimplementedOSReaderServer()
}

// UnimplementedOSReaderServer must be embedded to have forward compatible implementations.
type UnimplementedOSReaderServer struct {
}

func (UnimplementedOSReaderServer) GetOneByID(context.Context, *GetOneByIDRequest) (*GetOneByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneByID not implemented")
}
func (UnimplementedOSReaderServer) GetManyByIDs(context.Context, *GetManyByIDsRequest) (*GetManyByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManyByIDs not implemented")
}
func (UnimplementedOSReaderServer) ListByCursor(context.Context, *ListByCursorRequest) (*ListByCursorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByCursor not implemented")
}
func (UnimplementedOSReaderServer) ListByPage(context.Context, *ListByPageRequest) (*ListByPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByPage not implemented")
}
func (UnimplementedOSReaderServer) mustEmbedUnimplementedOSReaderServer() {}

// UnsafeOSReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSReaderServer will
// result in compilation errors.
type UnsafeOSReaderServer interface {
	mustEmbedUnimplementedOSReaderServer()
}

func RegisterOSReaderServer(s grpc.ServiceRegistrar, srv OSReaderServer) {
	s.RegisterService(&OSReader_ServiceDesc, srv)
}

func _OSReader_GetOneByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSReaderServer).GetOneByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/os.OSReader/GetOneByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSReaderServer).GetOneByID(ctx, req.(*GetOneByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSReader_GetManyByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManyByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSReaderServer).GetManyByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/os.OSReader/GetManyByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSReaderServer).GetManyByIDs(ctx, req.(*GetManyByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSReader_ListByCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSReaderServer).ListByCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/os.OSReader/ListByCursor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSReaderServer).ListByCursor(ctx, req.(*ListByCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSReader_ListByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSReaderServer).ListByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/os.OSReader/ListByPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSReaderServer).ListByPage(ctx, req.(*ListByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OSReader_ServiceDesc is the grpc.ServiceDesc for OSReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "os.OSReader",
	HandlerType: (*OSReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOneByID",
			Handler:    _OSReader_GetOneByID_Handler,
		},
		{
			MethodName: "GetManyByIDs",
			Handler:    _OSReader_GetManyByIDs_Handler,
		},
		{
			MethodName: "ListByCursor",
			Handler:    _OSReader_ListByCursor_Handler,
		},
		{
			MethodName: "ListByPage",
			Handler:    _OSReader_ListByPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/os/os_reader.proto",
}
