// Code generated by sqlc. DO NOT EDIT.

package make

import (
	"context"
)

type Querier interface {
	CountTotal(ctx context.Context) (int64, error)
	GetByID(ctx context.Context, id int64) (Make, error)
	GetManyByIDs(ctx context.Context, dollar_1 []int64) ([]Make, error)
	ListOffset(ctx context.Context, arg ListOffsetParams) ([]Make, error)
}

var _ Querier = (*Queries)(nil)
